spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biblioteca-digital
    username: postgres
    password: vieiradev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

server:
  port: 8080
